Repository nightingaleproject/vrdr-dotnet, pull requests merged in 2024-08, with the labels that each got.

#600 ci: add test coverage
  .github/workflows/run-tests.yml
  .gitignore
  README.md
  VRDR.Tests/DeathRecord.Tests.csproj
Labels: enhancement, maintenance

#605 ci: ignore patch dependency updates
  .github/dependabot.yml
Labels: maintenance

#608 fix: add null checks to extension values
  VRDR.Tests/DeathRecord.Tests.csproj
  VRDR.Tests/DeathRecord_Should.cs
  VRDR.Tests/fixtures/json/DeathRecordBirthRecordDataAbsent.json
  VRDR.Tests/fixtures/json/DeathRecordSubmissionMessage.json
  VRDR.Tests/fixtures/json/MissingExtensionValue.json
  VRDR/DeathRecord_util.cs
Labels: bug

#607 feat: add message header validation
  VRDR.Messaging/BaseMessage.cs
  VRDR.Tests/DeathRecord.Tests.csproj
  VRDR.Tests/Messaging_Should.cs
  VRDR.Tests/fixtures/json/MessageHeaderValidation.json
Labels: enhancement, vrdr
